package main

import (
	"fmt"
	"log"
	"reflect"

	"delivery-backend/internal/domain"
	"delivery-backend/pkg/config"

	"github.com/glebarez/sqlite"
	"gorm.io/driver/postgres"
	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/logger"
)

// main migrates the entire SQLite database to PostgreSQL.
//
// Safety guarantees:
//   - The SQLite source file is opened read-only (no writes/updates to old data).
//   - Schema is created on PostgreSQL via GORM AutoMigrate (PostgreSQL-compatible DDL).
//   - Data is copied inside a single transaction, ordered by foreign-key dependencies.
//   - INSERT ... ON CONFLICT DO NOTHING makes re-runs idempotent (no duplicates).
//   - Soft-deleted rows are preserved (read with Unscoped).
func main() {
	cfg := config.LoadConfig()

	// 1. Open SQLite source (read-only usage; we never write to it)
	src, err := gorm.Open(sqlite.Open(cfg.SQLitePath), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Silent),
	})
	if err != nil {
		log.Fatalf("فشل فتح SQLite المصدر: %v", err)
	}
	log.Printf("تم فتح SQLite المصدر: %s", cfg.SQLitePath)

	// 2. Open PostgreSQL destination
	dsn := fmt.Sprintf("host=%s user=%s password=%s dbname=%s port=%s sslmode=%s TimeZone=Asia/Riyadh",
		cfg.DBHost, cfg.DBUser, cfg.DBPassword, cfg.DBName, cfg.DBPort, cfg.DBSSLMode)
	dst, err := gorm.Open(postgres.Open(dsn), &gorm.Config{
		Logger: logger.Default.LogMode(logger.Warn),
	})
	if err != nil {
		log.Fatalf("فشل فتح PostgreSQL الوجهة: %v", err)
	}
	log.Printf("تم الاتصال بـ PostgreSQL: %s/%s", cfg.DBHost, cfg.DBName)

	// 3. Create schema on PostgreSQL (PostgreSQL-compatible DDL generated by GORM)
	if err := migrateSchema(dst); err != nil {
		log.Fatalf("فشل إنشاء الـ Schema: %v", err)
	}
	log.Println("تم إنشاء الـ Schema على PostgreSQL.")

	// 4. Copy data in foreign-key order inside a transaction
	if err := copyData(src, dst); err != nil {
		log.Fatalf("فشل نقل البيانات: %v", err)
	}

	// 5. Sync auto-increment sequences (defensive; PKs are UUID so normally a no-op)
	syncSequences(dst)

	log.Println("اكتمل نقل البيانات من SQLite إلى PostgreSQL بنجاح.")
}

// migrateSchema creates all tables on PostgreSQL using GORM AutoMigrate.
// The models already use PostgreSQL-compatible types (uuid, timestamptz, numeric, text).
func migrateSchema(dst *gorm.DB) error {
	return dst.AutoMigrate(
		&domain.Branch{},
		&domain.Admin{},
		&domain.Employee{},
		&domain.WorkSession{},
		&domain.AuditLog{},
		&domain.InventoryItem{},
		&domain.InventoryTransaction{},
		&domain.MaintenanceLog{},
		&domain.Investigation{},
		&domain.Attendance{},
		&domain.CustodyDay{},
		&domain.CustodyExpense{},
		&domain.CustodyLog{},
		&domain.AppSetting{},
	)
}

// copyData copies every table in an order that respects foreign keys.
func copyData(src, dst *gorm.DB) error {
	return dst.Transaction(func(tx *gorm.DB) error {
		// 1) No dependencies
		if err := copyRows(src, tx, "branches", &[]domain.Branch{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "inventory_items", &[]domain.InventoryItem{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "app_settings", &[]domain.AppSetting{}); err != nil {
			return err
		}

		// 2) Depend on branches
		if err := copyRows(src, tx, "admins", &[]domain.Admin{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "employees", &[]domain.Employee{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "audit_logs", &[]domain.AuditLog{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "custody_days", &[]domain.CustodyDay{}); err != nil {
			return err
		}

		// 3) Depend on employees
		if err := copyRows(src, tx, "work_sessions", &[]domain.WorkSession{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "maintenance_logs", &[]domain.MaintenanceLog{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "attendance", &[]domain.Attendance{}); err != nil {
			return err
		}

		// 4) Depend on employees + admins
		if err := copyRows(src, tx, "investigations", &[]domain.Investigation{}); err != nil {
			return err
		}

		// 5) Depend on items + employees + branches
		if err := copyRows(src, tx, "inventory_transactions", &[]domain.InventoryTransaction{}); err != nil {
			return err
		}

		// 6) Depend on custody_days
		if err := copyRows(src, tx, "custody_expenses", &[]domain.CustodyExpense{}); err != nil {
			return err
		}
		if err := copyRows(src, tx, "custody_logs", &[]domain.CustodyLog{}); err != nil {
			return err
		}

		return nil
	})
}

// copyRows reads all rows (including soft-deleted) from the source and inserts
// them into the destination using ON CONFLICT DO NOTHING for idempotency.
func copyRows(src, dst *gorm.DB, name string, destSlice interface{}) error {
	if err := src.Unscoped().Find(destSlice).Error; err != nil {
		return fmt.Errorf("قراءة %s: %w", name, err)
	}

	n := reflect.ValueOf(destSlice).Elem().Len()
	if n == 0 {
		log.Printf("  %-24s: 0 صف", name)
		return nil
	}

	if err := dst.Clauses(clause.OnConflict{DoNothing: true}).Create(destSlice).Error; err != nil {
		return fmt.Errorf("كتابة %s: %w", name, err)
	}
	log.Printf("  %-24s: %d صف", name, n)
	return nil
}

// syncSequences resets any SERIAL/identity sequences to the max existing value.
// In this schema all primary keys are UUID, so this is normally a no-op, but it
// keeps the migration future-proof if an integer sequence is ever added.
func syncSequences(db *gorm.DB) {
	type seqCol struct {
		TableName  string
		ColumnName string
	}
	var cols []seqCol
	err := db.Raw(`SELECT table_name, column_name FROM information_schema.columns
		WHERE table_schema = 'public' AND column_default LIKE 'nextval%'`).Scan(&cols).Error
	if err != nil {
		log.Printf("تحذير: تعذر فحص الـ Sequences: %v", err)
		return
	}
	if len(cols) == 0 {
		log.Println("لا توجد Sequences (SERIAL) — كل المفاتيح الأساسية من نوع UUID.")
		return
	}
	for _, c := range cols {
		q := fmt.Sprintf("SELECT setval(pg_get_serial_sequence('%s','%s'), COALESCE(MAX(%s), 1)) FROM %s",
			c.TableName, c.ColumnName, c.ColumnName, c.TableName)
		if err := db.Exec(q).Error; err != nil {
			log.Printf("تحذير: فشل تحديث sequence %s.%s: %v", c.TableName, c.ColumnName, err)
		} else {
			log.Printf("تم تحديث sequence لـ %s.%s", c.TableName, c.ColumnName)
		}
	}
}
